### ISSUE TITLE
Remember settings

### ISSUE THREAD

**Issue by fzimmermann89** [slaclab/slac-ood-jupyter#12]
Hi,
I don't know if this is the right place to suggest a small improvement -- or if this is even possible:

It would be great if the 'new session'-form would remember the 'custom singularity' and 'command to initiate' settings like it does for the requested resources. 

Thank you and have a great day,
Felix

**Comment by fzimmermann89** [comment]
It seems the setting is actually cached by ood, but in  https://github.com/slaclab/slac-ood-jupyter/blob/3d72f6326effc55db4e91cde6de75c96bab31a64/form.js#L102 it is overwritten. It would be nice, if selecting 'custom image' would use the cached command, which should be accessible for the script at $('#batch_connect_session_context_commands').text()

**Comment by yee379** [comment]
thanks for the suggestion. in the meantime, feel free to send a PR on form.yml.erb if its a common image that you and or your may want to share.

**Comment by fzimmermann89** [comment]
See #17
